# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ScrollLabelView' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'Masonry', '~> 1.0.1'

  target 'ScrollLabelViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScrollLabelViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
